# https://help.github.com/en/actions

# https://github.com/actions
# https://github.com/actions/checkout
# https://github.com/actions/setup-node

name: Node.js CI on Push

on: [push]

jobs:
  npm-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [^8.16.x, ^10.17.x, ^12.13.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Show node & npm versions, environment
      run: |
        node --version
        npm --version
        env
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
      env:
        CI: true
